"""Food Agent와 DB·외부 데이터 사이 통로.
구현체는 ORM·외부 API 가 연결된 뒤 같은 Protocol로 붙인다.
Food 의 쓰기 포트는 자기만 쓰고 읽는 둘(`daycare_meal` 수정·삭제 · 메뉴 카탈로그)이고,
호출마다 바로 commit 된다. 영양 합계·구간은 저장하지 않는다.
"""

from app.agents.food.store.inmemory import (
    InMemoryConsent,
    InMemoryDaycareMeals,
    InMemoryFoodDocs,
    InMemoryFoodMemory,
    InMemoryGrowth,
    InMemoryMenuCatalog,
    InMemoryMenuSource,
    InMemoryProfile,
    InMemorySafety,
    InMemorySuggestionHistory,
    in_memory_ports,
)
from app.agents.food.store.ports import (
    ChildProfileReader,
    ConsentReader,
    DaycareMealRow,
    DaycareMealStore,
    DaycareSlot,
    FoodDocReader,
    FoodDocRow,
    FoodMemoryReader,
    FoodObservation,
    FoodPorts,
    GrowthLogReader,
    Measurement,
    MenuCatalogRow,
    MenuCatalogStore,
    MenuSource,
    MenuSourceError,
    NutrientBand,
    NutritionFacts,
    SafetyEntry,
    SafetyLookupError,
    SafetyReader,
    SuggestionHistoryReader,
)

__all__ = [
    "ChildProfileReader",
    "ConsentReader",
    "DaycareMealRow",
    "DaycareMealStore",
    "DaycareSlot",
    "FoodDocReader",
    "FoodDocRow",
    "FoodMemoryReader",
    "FoodObservation",
    "FoodPorts",
    "GrowthLogReader",
    "InMemoryConsent",
    "InMemoryDaycareMeals",
    "InMemoryFoodDocs",
    "InMemoryFoodMemory",
    "InMemoryGrowth",
    "InMemoryMenuCatalog",
    "InMemoryMenuSource",
    "InMemoryProfile",
    "InMemorySafety",
    "InMemorySuggestionHistory",
    "Measurement",
    "MenuCatalogRow",
    "MenuCatalogStore",
    "MenuSource",
    "MenuSourceError",
    "NutrientBand",
    "NutritionFacts",
    "SafetyEntry",
    "SafetyLookupError",
    "SafetyReader",
    "SuggestionHistoryReader",
    "in_memory_ports",
]
