"""remove event status and expires_at, add event_item timestamps

Revision ID: 0f4480ddc873
Revises: e4f31ff97e3a
Create Date: 2026-09-20 19:26:42.297859

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f4480ddc873'
down_revision: Union[str, Sequence[str], None] = 'e4f31ff97e3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'status')
    op.drop_column('event', 'expires_at')
    op.add_column('event_item', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('event_item', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_item', 'updated_at')
    op.drop_column('event_item', 'created_at')
    op.add_column('event', sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('event', sa.Column('status', sa.VARCHAR(length=32), server_default=sa.text("'draft'::character varying"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
