"""add memory suggestion correction safety domain tables

Revision ID: 70e8ab2bf4b9
Revises: 69c9a5bdfe8f
Create Date: 2026-09-09 00:17:00.852629

"""
from typing import Sequence, Union

import pgvector.sqlalchemy.vector
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '70e8ab2bf4b9'
down_revision: Union[str, Sequence[str], None] = '69c9a5bdfe8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('diary_text', sa.Text(), nullable=True),
    sa.Column('image_urls', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['child.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('health_safety',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('allergy', 'chronic_disease', 'dietary_restriction', 'behavioral', 'environmental', 'other_medical', name='safety_kind', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('aliases', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('mild', 'moderate', 'severe', 'anaphylaxis', name='safety_severity', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('reactions', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('management', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('state', sa.Enum('active', 'retracted', name='safety_state', native_enum=False, create_constraint=True, length=32), server_default='active', nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['child.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['parent.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['parent.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('observation_health',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('confidence_source', sa.Enum('institution_notice', 'parent_direct', 'parent_hedged', 'parent_hearsay', name='confidence_source', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='observation_status', native_enum=False, create_constraint=True, length=32), server_default='active', nullable=False),
    sa.Column('observed_range', postgresql.DATERANGE(), nullable=False),
    sa.Column('source_writer', sa.UUID(), nullable=False),
    sa.Column('source_notice_id', sa.UUID(), nullable=True),
    sa.Column('symptom', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('severity', sa.Enum('mild', 'moderate', 'severe', 'emergency', name='health_severity', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('body_part', sa.Text(), nullable=True),
    sa.Column('suspected_trigger', sa.Text(), nullable=True),
    sa.Column('action_taken', sa.Text(), nullable=True),
    sa.Column('observed_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['child.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_writer'], ['parent.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile_affinity',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('merge_key', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('domain', sa.Enum('food', 'activity', 'education', name='memory_domain', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('state', sa.Enum('candidate', 'confirmed', 'archived', name='profile_state', native_enum=False, create_constraint=True, length=32), server_default='candidate', nullable=False),
    sa.Column('polarity', sa.SmallInteger(), nullable=True),
    sa.Column('strength', sa.Float(), server_default='0.3', nullable=False),
    sa.Column('last_observed_on', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['child.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suggestion',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('agent', sa.Enum('food', 'activity', 'education', 'health', name='suggestion_agent', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'approved', 'rejected', 'expired', name='suggestion_status', native_enum=False, create_constraint=True, length=32), server_default='draft', nullable=False),
    sa.Column('feedback', sa.Enum('liked', 'disliked', 'not_acted', name='suggestion_feedback', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('source_refs', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['child.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('correction',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('affinity_id', sa.UUID(), nullable=False),
    sa.Column('verdict', sa.Enum('confirm', 'once_only', 'outdated', 'wrong', name='correction_verdict', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['affinity_id'], ['profile_affinity.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('observation_activity',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('activity', sa.Text(), nullable=False),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('companions', sa.Text(), nullable=True),
    sa.Column('duration_min', sa.Integer(), nullable=True),
    sa.Column('engagement_level', sa.Enum('low', 'mid', 'high', name='engagement_level', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('affinity_id', sa.UUID(), nullable=True),
    sa.Column('polarity', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('strong_signals', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('confidence_source', sa.Enum('institution_notice', 'parent_direct', 'parent_hedged', 'parent_hearsay', name='confidence_source', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='observation_status', native_enum=False, create_constraint=True, length=32), server_default='active', nullable=False),
    sa.Column('observed_range', postgresql.DATERANGE(), nullable=False),
    sa.Column('source_writer', sa.UUID(), nullable=False),
    sa.Column('source_notice_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['affinity_id'], ['profile_affinity.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['child_id'], ['child.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_writer'], ['parent.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('observation_education',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('session_type', sa.Text(), nullable=True),
    sa.Column('duration_min', sa.Integer(), nullable=True),
    sa.Column('engagement_level', sa.Enum('low', 'mid', 'high', name='engagement_level', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('affinity_id', sa.UUID(), nullable=True),
    sa.Column('polarity', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('strong_signals', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('confidence_source', sa.Enum('institution_notice', 'parent_direct', 'parent_hedged', 'parent_hearsay', name='confidence_source', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='observation_status', native_enum=False, create_constraint=True, length=32), server_default='active', nullable=False),
    sa.Column('observed_range', postgresql.DATERANGE(), nullable=False),
    sa.Column('source_writer', sa.UUID(), nullable=False),
    sa.Column('source_notice_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['affinity_id'], ['profile_affinity.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['child_id'], ['child.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_writer'], ['parent.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('observation_food',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('action', sa.Text(), nullable=True),
    sa.Column('amount', sa.Text(), nullable=True),
    sa.Column('reaction', sa.Text(), nullable=True),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('affinity_id', sa.UUID(), nullable=True),
    sa.Column('polarity', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('strong_signals', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('confidence_source', sa.Enum('institution_notice', 'parent_direct', 'parent_hedged', 'parent_hearsay', name='confidence_source', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='observation_status', native_enum=False, create_constraint=True, length=32), server_default='active', nullable=False),
    sa.Column('observed_range', postgresql.DATERANGE(), nullable=False),
    sa.Column('source_writer', sa.UUID(), nullable=False),
    sa.Column('source_notice_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['affinity_id'], ['profile_affinity.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['child_id'], ['child.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_writer'], ['parent.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('observation_food')
    op.drop_table('observation_education')
    op.drop_table('observation_activity')
    op.drop_table('correction')
    op.drop_table('suggestion')
    op.drop_table('profile_affinity')
    op.drop_table('observation_health')
    op.drop_table('health_safety')
    op.drop_table('calendar')
    # ### end Alembic commands ###
