"""add observation_routine

food/education/activity 와 같은 ObservationCommon 컬럼 집합에, routine 전용 컬럼
(routine_category · context · assistance_level · completion_status · trigger) 을
더한다. status 는 f1c8b2d3a4e5 에서 이미 active/stand_alone/inactive 세 값으로
바뀐 뒤라 이 테이블은 처음부터 그 CHECK 로 생성된다.

correction.target_kind 의 observation_routine 값은 f1c8b2d3a4e5 에서 이미
추가돼 있다 — target_id 는 FK 가 아니라서 테이블이 없어도 값을 미리 넣을 수 있었다.

Revision ID: e4f31ff97e3a
Revises: f1c8b2d3a4e5
Create Date: 2026-09-19

"""
from typing import Sequence, Union

import pgvector.sqlalchemy.vector
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e4f31ff97e3a'
down_revision: Union[str, Sequence[str], None] = 'f1c8b2d3a4e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('observation_routine',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('routine_category', sa.Enum('self_care', 'mealtime', 'household_task', 'social_manner', 'habit', 'transition', name='routine_category', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('assistance_level', sa.Enum('independent', 'verbal_prompt', 'partial_assist', 'full_assist', name='assistance_level', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('completion_status', sa.Enum('completed', 'partial', 'refused', 'interrupted', name='completion_status', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('trigger', sa.Text(), nullable=True),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('affinity_id', sa.UUID(), nullable=True),
    sa.Column('polarity', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('strong_signals', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('confidence_source', sa.Enum('institution_notice', 'parent_direct', 'parent_hedged', 'parent_hearsay', name='confidence_source', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('status', sa.Enum('active', 'stand_alone', 'inactive', name='observation_status', native_enum=False, create_constraint=True, length=32), server_default='active', nullable=False),
    sa.Column('observed_range', postgresql.DATERANGE(), nullable=False),
    sa.Column('source_writer', sa.UUID(), nullable=True),
    sa.Column('source_notice_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['affinity_id'], ['profile_affinity.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['child_id'], ['child.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_writer'], ['parent.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('observation_routine')
    # ### end Alembic commands ###
